src/ExampleApp/ViewModels/FlightEditViewModel.cs
using Modles;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewModels
{
    public class FlightEditViewModel
    {

        public int Id { get; set; }
        [Required]
        [MaxLength(40,ErrorMessage = "Tekst je predugacak")]
       
        public string Name { get; set; }
        public FlighType FType { get; set; }
        public DateTime DateArrival { get; set; }

    }
}

src/ExampleApp/ViewModels/HomePageViewModel.cs
using Modles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewModels
{
    public class HomePageViewModel
    {
        public IEnumerable<Flights> Flights { get; set; }
        public string Message { get; set; }
    }
}

src/ExampleApp/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }

        [Required, DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }
    }
}

src/ExampleApp/ViewModels/RegisterUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewModels
{
    public class RegisterUserViewModel
    {
        [Required, MaxLength(256)]
        public string Username { get; set; }

        [Required, DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password), Compare(nameof(Password))]
        public string ConfirmPassword { get; set; }
    }
}

src/ExampleApp/Controllers/AccountController.cs
using ExampleApp.Auth;
using ExampleApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Modles;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.Controllers
{
    public class AccountController : Controller
    {
        private SignInManager<User> _signInManager;
        private UserManager<User> _userManager;

        public AccountController(UserManager<User> userManager,
                                 SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        //[Permission("Da je user")]
        public async Task<IActionResult> Register(RegisterUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User { UserName = model.Username };

                var createResult = await _userManager.CreateAsync(user, model.Password);
                if (createResult.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in createResult.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var loginResult = await _signInManager.PasswordSignInAsync(
                                            model.Username, model.Password,
                                            model.RememberMe, false);
                if (loginResult.Succeeded)
                {
                    if (Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Could not login");
            return View(model);
        }

    }
}

src/ExampleApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Services;
using ExampleApp.ViewModels;
using Modles;
using Microsoft.AspNetCore.Authorization;

namespace ExampleApp.Controllers
{
    [Authorize]
    [Route("[controller]/[action]/{id?}")]
    public class HomeController : IndexBaseController
    {
        IFlightsData _flightsData;
        public HomeController(IFlightsData flightsData)
        {
            _flightsData = flightsData;
        }

        public override ViewResult Index()
        {
            var model = new HomePageViewModel();
            model.Flights = _flightsData.GetAll();
            model.Message = "controller message";

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _flightsData.Get(id);
            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FlightEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newFlight = new Flights();
                newFlight.FType = model.FType;
                newFlight.Name = model.Name;
                newFlight = _flightsData.Add(newFlight);

                return RedirectToAction("Details", new { id = newFlight.Id });
            }
            return View();
        }
    }
}

src/ExampleApp/Controllers/IndexBaseController.cs
using ExampleApp.ActionResults;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.Controllers
{
    public abstract class IndexBaseController : Controller

    {


        public IndexBaseController()
        {
        }

        //public virtual FileActionResult Index()
        //{
        //    return new FileActionResult(@"");
        //}


        public virtual ViewResult Index()
        {
            return View();
        }

        [HttpPost(Name = "Index")]
        public virtual string Index_Post()
        {
            return "IndexPost";
        }
    }
}

src/ExampleApp/ViewComponents/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewComponents
{
    public class TestViewComponent : ViewComponent
    {
        private IConfigurationReader _configurationReader;

        public TestViewComponent(IConfigurationReader configurationReader)
        {
            _configurationReader = configurationReader;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = _configurationReader.ReadConnectionString();
            return Task.FromResult<IViewComponentResult>(View("Default", model));
        }
    }
}

src/ExampleApp/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExampleApp.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/ExampleApp/Views/Home/Create.cshtml
@using Modles
@model Flights

@{
        ViewBag.Title = "Krairanje";
}

<div>

    <h1>@ViewBag.Title</h1>

    <div>
        <form asp-action="Create" asp-controller="Home" method="post">

            <div>
                <label asp-for="Name" />
                @*@Html.LabelFor(m => m.Name)*@
                <input type="text" asp-for="Name" placeholder="Name" />
                <span asp-validation-for="Name"></span>
                @*@Html.EditorFor(m => m.Name)
                    @Html.ValidationMessageFor(m => m.Name)*@
            </div>
            <div>
                @Html.LabelFor(m => m.FType)
                @*@Html.DropDownListFor(m => m.FType, Html.GetEnumSelectList(typeof(FlighType)))*@
                <select asp-for="FType" asp-items="Html.GetEnumSelectList(typeof(FlighType))"></select>
                @Html.ValidationMessageFor(m => m.FType)
            </div>
            <div>
                <input type="submit" value="Save!" />
            </div>
        </form>

        <a class="btn btn-primary" asp-controller="Home" asp-action="Index">
            <i class="fa fa-arrow-left"></i>
            Back to list
        </a>

    </div>

</div>
@section footer
{
    <div>this is footer</div>
}

src/ExampleApp/Views/Home/Details.cshtml
@using Modles
@model Flights

<h1>@Model.Name</h1>

<div>
    Id: @Model.Id
</div>
<div>
    Name: @Html.DisplayFor(x => x.Name)
</div>
<div>
    Cuisine: @Model.FType
</div>
<div>
    @Html.ActionLink("Home", "Index")
</div>

src/ExampleApp/Views/Home/Index.cshtml
@model ExampleApp.ViewModels.HomePageViewModel

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Flights</title>
</head>
<body>
    <h1>Welcome!</h1>
    <h3>@Model.Message</h3>
    <table>
        @foreach (var flight in Model.Flights)
        {
            @*<tr>
                    <td>
                        <a href="/home/details/@flight.Id">Details</a>
                        @Html.ActionLink("View", "Details", new { id = flight.Id })
                        <a asp-action="Details" asp-route-id="@flight.Id">Detalji tag</a>
                    </td>
                    <td>@flight.Name</td>
                </tr>*@

            @Html.Partial("_FlightDetail",flight)

        }
        @Html.SubmitButton("aaaa")
        <environment names="Development">
            <cache expires-after="@TimeSpan.FromMinutes(10)">
                *last updated  @DateTime.Now.ToLocalTime()
            </cache>
        </environment>
        <environment names="Production">
            *last updated  @DateTime.Now.ToLocalTime()
        </environment>
    </table>
    @Html.ActionLink("Create", "Create")

</body>
</html>

src/ExampleApp/Views/Home/_Create.cshtml
@using Modles
@model Flights

    @{
        ViewBag.Title = "Krairanje";
    }

<div> 
    
    <h1>@ViewBag.Title</h1>
    
    <div>
        @using (Html.BeginForm())
        { 
            <div>                           
                @Html.LabelFor(m => m.Name)
                @Html.EditorFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div>
                @Html.LabelFor(m => m.FType)
                @Html.DropDownListFor(m => m.FType, Html.GetEnumSelectList(typeof(FlighType)))
                @Html.ValidationMessageFor(m => m.FType)
            </div>
            <div>
                <input type="submit" value="Save!" />
            </div>
        }

    </div>

</div>
@section footer
{
    <div>this is footer</div>
 }

src/ExampleApp/Views/Home/_FlightDetail.cshtml
@model Flights
<tr>
    <td>
        <a href="/home/details/@Model.Id">Details</a>
        @Html.ActionLink("View", "Details", new { id = Model.Id })
        <a asp-action="Details" asp-route-id="@Model.Id">Detalji tag</a>
    </td>
    <td>@Model.Name</td>
</tr>

src/ExampleApp/Views/Shared/Components/Greeting/Default.cshtml
@model String
@inject Services.IConfigurationReader confReader
<section>
    <small>@Model</small>
    @confReader.ReadOption1()
</section>

src/ExampleApp/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <span>Hello, @User.Identity.Name</span>
    <form method="post" asp-controller="Account" asp-action="Logout" asp-antiforgery="true">
        <input type="submit" value="Logout"/>
    </form>
}
else
{
    <a asp-controller="Account" asp-action="Register">Register</a>
    <a asp-controller="Account" asp-action="Login">Login</a>
}

src/ExampleApp/Views/Shared/DisplayTemplates/String.cshtml
@model String
@Model.ToUpper()

src/ExampleApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Flights</a>
            </div>
            <div class="navbar-right">
                @*@await Component.InvokeAsync("LoginLogout")*@
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            @await Component.InvokeAsync("Test")
        </footer>
    </div>
    
    <script src="/node_modules/jquery/dist/jquery.js"></script>
    <script src="/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    <script src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</body>
</html>

src/ExampleApp/Views/Shared/_Layoutnew.cshtml
@using System.Security.Claims
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment names="Development">
        <link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.css">
    </environment>
    <environment names="Staging, Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="/node_modules/bootstrap/dist/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">Flights admin</a>
            </div>
            <div class="nav navbar-nav navbar-right">
                @*@if (User.IsSignedIn())
                {
                    <form method="post" asp-controller="Account" asp-action="Logout" class="navbar-form">
                        @User.GetUserName()
                        <input type="submit" value="Logout" class="btn btn-danger" />
                    </form>
                }
                else
                {
                    <a class="btn btn-default btn-xs navbar-btn" asp-controller="Account" asp-action="Login">Login</a>
                    <a class="btn btn-default btn-xs navbar-btn" asp-controller="Account" asp-action="Register">Register</a>
                }*@
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", false)
            @*@Component.Invoke("Test")*@
        </footer>
    </div>

    <environment name="Development">
        <script src="/node_modules/jquery/dist/jquery.js"></script>
        <script src="/node_modules/jquery-validation/dist/jquery.validate.js"></script>
        <script src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>

    <environment names="Staging, Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="/node_modules/jquery/dist/jquery.js"
                asp-fallback-test="window.jQuery">

        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                asp-fallback-src="/node_modules/jquery-validation/dist/jquery.validate.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="/node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
    </environment>

</body>
</html>